language: java
jdk:
  - oraclejdk8
#addons:
#  sonarcloud:
#    organization: "tmp" #
#    token:
#      secure: "ksdAQnt8GuziAxw5P3QvVb8...=" # ili da stavis $SONAR_TOKEN
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY # ili da stavis sirovu vrednost kljuca
  app: tim91 # naziv svoje aplikacije
#script:
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
