language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "nikolinagasic"
    token:
      secure: $SONAR_API_KEY
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: tim91zis
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
